### ISSUE TITLE
[Question] background tracking notification

### ISSUE THREAD

**Issue by freeubi** [sobri909/LocoKit#23]
Can I somehow re-enable the ios blue bar notification while my app is tracking GPS? 

I often forget to stop the exercise tracking, so I have  +15h exercise. I am afraid that the users will do this too :/

**Comment by sobri909** [comment]
There's `CLLocationManager.showsBackgroundLocationIndicator` which might do what you want. 

So you'd do something like: 

```swift
LocomotionManager.highlander.locationManager.showsBackgroundLocationIndicator = true
```

**Comment by freeubi** [comment]
Thanks!
