### ISSUE TITLE
Couldn't build LocoKit Develop branch with Xcode 11.2

### ISSUE THREAD

**Issue by zhavoronkov** [sobri909/LocoKit#66]
Receiving the error

> Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2 compiler: /Pods/LocoKitCore/LocoKitCore.framework/Modules/LocoKitCore.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

It seems that you need to recompile LocoKitCore framework with BUILD_LIBRARY_FOR_DISTRIBUTION=YES flag

**Comment by sobri909** [comment]
Ok, this is done now. Apologies for the long delay!
