### ISSUE TITLE
Couldn't build LocoKit Develop branch with Xcode 11.3

### ISSUE THREAD

**Issue by StasMalinovsky** [sobri909/LocoKit#67]
Could you please recompile LocoKitCore framework for the latest versions of Xcode?

**Comment by sobri909** [comment]
Apologies for the long delay on this! I've put a new LocoKitCore build live now, ready for Xcode 11.3.1.

I'll likely also merge the develop branch into master today, given that the only thing holding it back is lack of documentation, and I'm just not going to get the time to fill in the missing documentation any time soon. 

If I do merge up to master, I'll send out a proper CocoaPods release, with new major version number, etc. But the develop branch will still continue to be active, and essentially stable, given that it's where I push all the commits that have gone live in the latest Arc App releases.
