### ISSUE TITLE
Unable to build in Swift 5

### ISSUE THREAD

**Issue by voyager163** [sobri909/LocoKit#71]
Module compiled with Swift 4.1 cannot be imported by the Swift 5.1.3 compiler: /Users/XXXXXX/Downloads/LocoKit-master/Pods/LocoKitCore/LocoKitCore.framework/Modules/LocoKitCore.swiftmodule/arm.swiftmodule

**Comment by sobri909** [comment]
Hi! Make sure that you are using the develop branch. Thanks.
