### ISSUE TITLE
can I use it in OC project？

### ISSUE THREAD

**Issue by ouzs** [sobri909/LocoKit#9]
I try use it in my OC project，but I  can't found LocomotionSample  method in Class LocomotionManager. I try to add @objc in this method ,but tips 'Method cannot be marked @objc because its result type cannot be represented in Objective-C'  when I Compile，pls help me，thx，very much！！！

**Comment by sobri909** [comment]
To use it in an Objective-C project I recommend making a small wrapper class in Swift that handles the portion of the API that you need to use. For example:

```swift
@objc class TimelineWrapper: NSObject {

    var timeline = TimelineManager()

    init() {
        super.init()
        timeline.startRecording()
    }

    ...
}
```

Although it very much depends how much of ArcKit you need to use directly, and which parts of the API. Can you give a quick description of which ArcKit features you intend to use in your project?
